name: Build GBA ROM

on:
  push:
    branches: ['**']  # All branches
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM toolchain
        run: |
          sudo apt-get update
